"""Native immutable interface to the deterministic batched riichi env."""

from ._riichi import (
    ABSENT_SENTINEL,
    ACTION_KIND_CODES,
    DECISION_SCHEMA_VERSION,
    EVENT_SCHEMA_VERSION,
    FRAME_STATUS_CODES,
    HAND_ANALYSIS_VERSION,
    MJAI_EVENT_NAMES,
    NATIVE_BUILD_PROFILE,
    RNG_PROFILE,
    RNG_PROFILE_ID,
    RULES_PROFILE,
    RULES_PROFILE_ID,
    SHANTEN_UNAVAILABLE,
    SNAPSHOT_SCHEMA_VERSION,
    STATE_SCHEMA_VERSION,
    TENHOU_RULES_PROFILE,
    TENHOU_RULES_PROFILE_ID,
    ActionSelection,
    ActionKind,
    ActionCandidate,
    ActionSpace,
    Event,
    HandAnalysis,
    HiddenState,
    Meld,
    RiverTile,
    ReplayEvent,
    ReplayHanchan,
    InferenceRequest,
    RolloutChunk,
    RolloutEngine,
    State,
    Transition,
    _Env,
    analyze_hands,
    ensure_shanten_cache,
)

Env = _Env

ACTION_KIND_CODES = dict(ACTION_KIND_CODES)
FRAME_STATUS_CODES = dict(FRAME_STATUS_CODES)
MJAI_EVENT_NAMES = dict(MJAI_EVENT_NAMES)

__all__ = [
    "Env",
    "State",
    "Event",
    "ActionSpace",
    "ActionSelection",
    "ActionKind",
    "ActionCandidate",
    "Transition",
    "Meld",
    "RiverTile",
    "ReplayEvent",
    "ReplayHanchan",
    "InferenceRequest",
    "RolloutChunk",
    "RolloutEngine",
    "HiddenState",
    "HandAnalysis",
    "analyze_hands",
    "ensure_shanten_cache",
    "STATE_SCHEMA_VERSION",
    "EVENT_SCHEMA_VERSION",
    "DECISION_SCHEMA_VERSION",
    "HAND_ANALYSIS_VERSION",
    "NATIVE_BUILD_PROFILE",
    "SNAPSHOT_SCHEMA_VERSION",
    "RULES_PROFILE",
    "RULES_PROFILE_ID",
    "TENHOU_RULES_PROFILE",
    "TENHOU_RULES_PROFILE_ID",
    "RNG_PROFILE",
    "RNG_PROFILE_ID",
    "ABSENT_SENTINEL",
    "SHANTEN_UNAVAILABLE",
    "ACTION_KIND_CODES",
    "FRAME_STATUS_CODES",
    "MJAI_EVENT_NAMES",
]
